<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="0" total="14" passed="12">
  <reporter-output>
  </reporter-output>
  <suite name="All Test Suite" duration-ms="314" started-at="2020-07-26T15:06:43 CST" finished-at="2020-07-26T15:06:44 CST">
    <groups>
    </groups>
    <test name="D:/IT/ProjectFile/EdusohoTestNGM" duration-ms="314" started-at="2020-07-26T15:06:43 CST" finished-at="2020-07-26T15:06:44 CST">
      <class name="com.testng.demo.demo.NewTest">
        <test-method status="PASS" signature="f1(java.lang.Integer, java.lang.String)[pri:0, instance:com.testng.demo.demo.NewTest@5a4aa2f2]" name="f1" duration-ms="3" started-at="2020-07-26T15:06:44 CST" data-provider="dp" finished-at="2020-07-26T15:06:44 CST">
          <params>
            <param index="0">
              <value>
                <![CDATA[1]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[a]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- f1 -->
        <test-method status="PASS" signature="f1(java.lang.Integer, java.lang.String)[pri:0, instance:com.testng.demo.demo.NewTest@5a4aa2f2]" name="f1" duration-ms="2" started-at="2020-07-26T15:06:44 CST" data-provider="dp" finished-at="2020-07-26T15:06:44 CST">
          <params>
            <param index="0">
              <value>
                <![CDATA[2]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[b]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- f1 -->
      </class> <!-- com.testng.demo.demo.NewTest -->
      <class name="com.testng.demo.TC4">
        <test-method status="PASS" signature="clas01()[pri:0, instance:com.testng.demo.TC4@3f200884]" name="clas01" duration-ms="3" started-at="2020-07-26T15:06:44 CST" finished-at="2020-07-26T15:06:44 CST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- clas01 -->
        <test-method status="FAIL" signature="clas02()[pri:0, instance:com.testng.demo.TC4@3f200884]" name="clas02" duration-ms="2" started-at="2020-07-26T15:06:44 CST" finished-at="2020-07-26T15:06:44 CST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [测试2] but found [测试1]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [测试2] but found [测试1]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at org.testng.Assert.assertEquals(Assert.java:585)
at com.testng.demo.TC4.clas02(TC4.java:23)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:110)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- clas02 -->
      </class> <!-- com.testng.demo.TC4 -->
      <class name="com.testng.demo.TC5">
        <test-method status="PASS" signature="clas01()[pri:0, instance:com.testng.demo.TC5@4d339552]" name="clas01" duration-ms="3" started-at="2020-07-26T15:06:44 CST" finished-at="2020-07-26T15:06:44 CST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- clas01 -->
        <test-method status="PASS" signature="clas02()[pri:0, instance:com.testng.demo.TC5@4d339552]" name="clas02" duration-ms="2" started-at="2020-07-26T15:06:44 CST" finished-at="2020-07-26T15:06:44 CST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- clas02 -->
      </class> <!-- com.testng.demo.TC5 -->
      <class name="com.testng.demo.TC6">
        <test-method status="PASS" signature="clas01()[pri:0, instance:com.testng.demo.TC6@f0f2775]" name="clas01" duration-ms="2" started-at="2020-07-26T15:06:44 CST" finished-at="2020-07-26T15:06:44 CST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- clas01 -->
        <test-method status="PASS" signature="clas02()[pri:0, instance:com.testng.demo.TC6@f0f2775]" name="clas02" duration-ms="2" started-at="2020-07-26T15:06:44 CST" finished-at="2020-07-26T15:06:44 CST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- clas02 -->
      </class> <!-- com.testng.demo.TC6 -->
      <class name="com.testng.demo.TC1">
        <test-method status="PASS" signature="clas01()[pri:0, instance:com.testng.demo.TC1@b7f23d9]" name="clas01" duration-ms="74" started-at="2020-07-26T15:06:43 CST" finished-at="2020-07-26T15:06:43 CST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- clas01 -->
        <test-method status="PASS" signature="clas02()[pri:0, instance:com.testng.demo.TC1@b7f23d9]" name="clas02" duration-ms="4" started-at="2020-07-26T15:06:43 CST" finished-at="2020-07-26T15:06:43 CST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- clas02 -->
      </class> <!-- com.testng.demo.TC1 -->
      <class name="com.testng.demo.TC2">
        <test-method status="PASS" signature="clas03()[pri:0, instance:com.testng.demo.TC2@61d47554]" name="clas03" duration-ms="3" started-at="2020-07-26T15:06:43 CST" finished-at="2020-07-26T15:06:43 CST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- clas03 -->
        <test-method status="PASS" signature="clas04()[pri:0, instance:com.testng.demo.TC2@61d47554]" name="clas04" duration-ms="3" started-at="2020-07-26T15:06:43 CST" finished-at="2020-07-26T15:06:43 CST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- clas04 -->
      </class> <!-- com.testng.demo.TC2 -->
      <class name="com.testng.demo.TC3">
        <test-method status="PASS" signature="clas01()[pri:0, instance:com.testng.demo.TC3@69b794e2]" name="clas01" duration-ms="2" started-at="2020-07-26T15:06:44 CST" finished-at="2020-07-26T15:06:44 CST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- clas01 -->
        <test-method status="FAIL" signature="clas02()[pri:0, instance:com.testng.demo.TC3@69b794e2]" name="clas02" duration-ms="3" started-at="2020-07-26T15:06:44 CST" finished-at="2020-07-26T15:06:44 CST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [测试2] but found [测试1]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [测试2] but found [测试1]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at org.testng.Assert.assertEquals(Assert.java:585)
at com.testng.demo.TC3.clas02(TC3.java:21)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:110)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- clas02 -->
      </class> <!-- com.testng.demo.TC3 -->
    </test> <!-- D:/IT/ProjectFile/EdusohoTestNGM -->
  </suite> <!-- All Test Suite -->
</testng-results>
